spring:
  datasource:
    url: jdbc:postgresql://46.101.224.6:5432/rspcm
    username: endragon
    password: 3875671

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    username: endragon
    password: 3875671
    host: 46.101.224.6
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          max-interval: 10000ms
          multiplier: 2

  springdoc:
    api-docs:
      enabled: true
      path: /swagger-ui.html

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always

  eureka:
    instance:
      hostname: auth-service
    client:
      enabled: ${EUREKA_CLIENT_ENABLED:true}
      service-url:
        defaultZone: http://167.71.34.190:8761/eureka/

otp:
  retry-wait-time: 60
  retry-count: 3
  time-to-live: 120
  block-duration: 600

notification:
  eskiz:
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

token:
  expiration: 86400
  token: nC1zvT1QWqD7jVqz9Z2Dq9cF4o3j1+gZB6gXx8Llx9A=

outbox:
  publisher:
    enabled: true
    fixed-delay-ms: 5000
    batch-size: 100
    max-attempts: 20
    retry-delay-seconds: 30

