spring:
  datasource:
    url: jdbc:postgresql://161.35.72.98:5432/rspcm
    username: user
    password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  rabbitmq:
    username: admin
    password: admin
    host: 161.35.72.98
    port: 5672
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000ms
          max-attempts: 3
          max-interval: 10000ms
          multiplier: 2
  data:
    redis:
      host: 161.35.72.98
      port: 6379
      password: password

  springdoc:
    api-docs:
      enabled: true
      path: /swagger-ui.html

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
    hostname: auth-service

  client:
    enabled: ${EUREKA_CLIENT_ENABLED:false}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

otp:
  retry-wait-time: 60
  retry-count: 3
  time-to-live: 120
  block-duration: 600

notification:
  eskiz:
    token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

token:
  expiration: 86400
  token: nC1zvT1QWqD7jVqz9Z2Dq9cF4o3j1+gZB6gXx8Llx9A=

outbox:
  publisher:
    enabled: true
    fixed-delay-ms: 5000
    batch-size: 50
    max-attempts: 10
    retry-delay-seconds: 30

